### PR TITLE
Transition to bindgen bindings.

### LINKED ISSUE #28: libui since 13 June 2016 uses `int` instead of `intmax_t` in most functions
... and this includes `uiNewSpinbox`.

(https://github.com/andlabs/libui/compare/857bbbf5062f86ef7c7ac175a1505b39088097e7...fa4542f217f1557490ba4b7dddf493ddf616b5d7)

In `iui 0.3.0`, `Spinbox::new_unlimited()` will forward to `Spinbox::new(i64::MIN, i64::MAX)`. However, as `uiNewSpinbox` takes the 32-bit `int` instead of the 64-bit `intmax_t`, the C library will truncate the numbers and read as `uiNewSpinbox(0, -1)`, which creates a spinbox with only two valid values: -1 and 0.

### PR DESCRIPTION
**Pull request by NoraCodes**
This ensures that `iui` and `ui-sys` will be accurately tracking `libui`'s development, and allows us to be more agile in terms of implementing new (and experimental) features.

Closes #28 

@kennytm review would be appreciated

### CODE REVIEW

**Review by kennytm — APPROVED** [review]
LGTM.

**Comment by LordZane** [comment]
What's stopping this from being merged? The latest appveyor build passes, and it seems this is blocking all the new features like radio buttons and tables (tables added yesterday)

**Comment by NoraCodes** [comment]
The primary blocker is my lack of Windows testing platforms. I currently have an old laptop which can't really support simultaneous development with a VM so it's difficult for me to test. If someone could confirm that this compiles and the examples work on Windows I could merge it now; otherwise I'll need to wait until I'm back at school to use one of the school machines.

**Comment by LordZane** [comment]
Will test in a bit when my compiler finishes updating, but it works with the one im currently on (1.26.1) from like 3 months ago

**Comment by NoraCodes** [comment]
Great, thanks so much! Assuming the both your build and the Appveyor build pass, I'll merge it.

EDIT: We still have the issue that the types are different on Windows, apparently?

```
error[E0308]: match arms have incompatible types
   --> iui\src\controls\layout.rs:283:9
    |
283 | /         match self {
284 | |             Fill => ui_sys::uiAlignFill,
    | |                     ------------------- match arm with an incompatible type
285 | |             Start => ui_sys::uiAlignStart,
286 | |             Center => ui_sys::uiAlignCenter,
287 | |             End => ui_sys::uiAlignEnd 
288 | |         }
    | |_________^ expected u32, found i32
error[E0308]: match arms have incompatible types
   --> iui\src\controls\layout.rs:283:9
    |
283 | /         match self {
284 | |             Fill => ui_sys::uiAlignFill,
    | |                     ------------------- match arm with an incompatible type
285 | |             Start => ui_sys::uiAlignStart,
286 | |             Center => ui_sys::uiAlignCenter,
287 | |             End => ui_sys::uiAlignEnd 
288 | |         }
    | |_________^ expected u32, found i32
error[E0308]: match arms have incompatible types
   --> iui\src\controls\layout.rs:308:9
    |
308 | /         match self {
309 | |             Leading => ui_sys::uiAtLeading,
    | |                        ------------------- match arm with an incompatible type
310 | |             Top => ui_sys::uiAtTop,
311 | |             Trailing => ui_sys::uiAtTrailing,
312 | |             Bottom => ui_sys::uiAtBottom 
313 | |         }
    | |_________^ expected u32, found i32
error[E0308]: match arms have incompatible types
   --> iui\src\controls\layout.rs:308:9
    |
308 | /         match self {
309 | |             Leading => ui_sys::uiAtLeading,
    | |                        ------------------- match arm with an incompatible type
310 | |             Top => ui_sys::uiAtTop,
311 | |             Trailing => ui_sys::uiAtTrailing,
312 | |             Bottom => ui_sys::uiAtBottom 
313 | |         }
    | |_________^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:29:27
   |
29 |                     Type: ui_sys::uiDrawBrushTypeSolid,
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:48:27
   |
48 |                     Type: ui_sys::uiDrawBrushTypeLinearGradient,
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:67:27
   |
67 |                     Type: ui_sys::uiDrawBrushTypeRadialGradient,
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:88:31
   |
88 |                         Type: ui_sys::uiDrawBrushTypeImage,
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:29:27
   |
29 |                     Type: ui_sys::uiDrawBrushTypeSolid,
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:48:27
   |
48 |                     Type: ui_sys::uiDrawBrushTypeLinearGradient,
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:67:27
   |
67 |                     Type: ui_sys::uiDrawBrushTypeRadialGradient,
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error[E0308]: mismatched types
  --> iui\src\draw\brush.rs:88:31
   |
88 |                         Type: ui_sys::uiDrawBrushTypeImage,
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u32, found i32
error: aborting due to 6 previous errors

```

**Comment by LordZane** [comment]
Weird, I read the issues on bindgen and it seems like it's an issue on libui's side, but on my computer, the examples work fine and the library compiles.

stable-x86_64-pc-windows-msvc (default)
rustc 1.28.0 (9634041f0 2018-07-30)

**Comment by NoraCodes** [comment]
No, it's an issue in Microsoft's compiler. I'll use a workaround, should be implemented Soon :tm:

**Comment by zaynetro** [comment]
This looks great! Any updates on your "workaround" progress? :)

**Comment by NoraCodes** [comment]
Currently wading through schoolwork but I hope to have it release-quality soon

**Comment by NoraCodes** [comment]
@LordZane @zaynetro This looks like it should work; could you test on your Windows machines?

Many thanks!

**Comment by LordZane** [comment]
@LeoTindall What has changed? I actually switched to gtk-rs since then, but I can test an older version of my app. What do you need me to test?

**Comment by NoraCodes** [comment]
Just test that it compiles. It works on appveyor.

**Comment by zaynetro** [comment]
@LeoTindall I don't have a Windows machine :( Nice to see the progress!

**Comment by LordZane** [comment]
Works fine!

**Comment by NoraCodes** [comment]
Great, thank you! Merging.
